language: php

env:
    global:
        - setup=stable

matrix:
    fast_finish: true
    include:
        -   php: 7.2
#        -   php: 7.2
#            env: setup=lowest

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - sudo apt-get install -y wget
    - travis_retry composer self-update

install:
    - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
    - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --access-token="586a391e0912058c530126f8ebe237e7881c4010b61687d05706ab597c0a7a66" --format=php-clover coverage.clover
